library(tidyverse)
library(plotly)
library(janitor)

mferrana0 <- lm(ncadt ~ pib_aa + desemp, data = ferrana)
mferrana0.5 <- lm(ncadt ~ govop, data = ferrana)
mferrana1 <- lm(ncadt ~ pib_aa + govop, data = ferrana)
mferrana2 <- lm(ncadt ~ desemp + govop, data = ferrana)
mferrana3 <- lm(ncadt ~ pib_aa + desemp + govop, data = ferrana)
mferrana4 <- lm(nests ~ pib_aa + govop, data = ferrana)
mferrana5 <- lm(nests ~ desemp + govop, data = ferrana)
mferrana6 <- lm(nests ~ pib_aa + desemp + govop, data = ferrana)
mferrana7 <- lm(ncadt ~ pib_aa * desemp + pib_aa + desemp + govop, data = ferrana)
mferrana8 <- lm(nests ~ pib_aa * desemp + pib_aa + desemp + govop, data = ferrana)

